/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-11-10 15:46:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class addressPaymentForOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("<title>Payment page</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/responsive-style.css\">\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/cartstyle.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/yourcartcss.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\tbody {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background:white;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: 100% 110%\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    padding: 30px 40px;\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("    margin-bottom: 60px;\r\n");
      out.write("    border: none !important;\r\n");
      out.write("    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.2)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-text {\r\n");
      out.write("    color: #00BCD4\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control-label {\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input,\r\n");
      out.write("textarea,\r\n");
      out.write("button {\r\n");
      out.write("    padding: 8px 15px;\r\n");
      out.write("    border-radius: 5px !important;\r\n");
      out.write("    margin: 5px 0px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 300\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus,\r\n");
      out.write("textarea:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    border: 1px solid #00BCD4;\r\n");
      out.write("    outline-width: 0;\r\n");
      out.write("    font-weight: 400\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block {\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    cursor: pointer\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block:hover {\r\n");
      out.write("    color: #fff !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    outline-width: 0\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tfont-family: cursive;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("<script>\r\n");
      out.write("if(window.history.forward(1) !=null)\r\n");
      out.write("\twindow.history.forward(1);\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("\t\t<nav class=\"navbar  navbar-expand-lg navigation-wrap \">\r\n");
      out.write("\t\t\t\t\t <img src=\"images/Viplogo.png\" class=\"img-fluid\" style=\"position:absolute;margin-left:20px;\">\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\" >\r\n");
      out.write("\t\t\t\t\t\t<a class=\"main-btn\" href=\"homepage.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"main-btn\" href=\"myCart.jsp\">Back</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("\t\t\t\t <img src=\"images/organicLogo.png\" class=\"img-fluid\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"main-btn\" href=\"Logout.jsp\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");

String email= session.getAttribute("email").toString();
int total=0;
int sno=0;
try {
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/viporg", "root", "root");
	Statement st=con.createStatement();
	ResultSet rs1=st.executeQuery("select sum(total) from cart where email='"+email+"' and address is NULL");
	while(rs1.next())
	{
		total=rs1.getInt(1);

	} 
	
	 ResultSet rs2=st.executeQuery("select *from users where email='"+email+"' ");
     while(rs2.next())
     {
  	 
     
      out.write("       \r\n");
      out.write("<h2 style=\"position:absolute;margin-left:80px;top:105px;color:#00a149\">CONGRATULATIONS ");
out.println(email);
      out.write("YOU AVAIL 10% DISCOUNT ON TOTAL PRICE!</h2>\r\n");
      out.write("<div class=\"container\" style=\"position:absolute;top:59px;margin-left:150px\" >\r\n");
      out.write("<form action=\"addresspaymentpage.jsp\" method=\"post\">\r\n");
      out.write("\t\t<h2 style=\"margin-left:150px;top:130px;position:absolute;font-size:25px\" >You pay(after 10% discount):<h2 style=\"margin-left:500px;top:130px;position:absolute;font-size:32px;color: black\" > Rs.");
out.println(total-(total/10)); 
      out.write("</h2> </h2>\r\n");
      out.write("\t<h3 style=\"margin-left:150px;top:180px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">Enter Address</h3>\r\n");
      out.write("\t<input style=\"margin-left:360px;border:2px solid;top:175px;position:absolute\" type = \"text\" name=\"address\" value=\"");
      out.print(rs2.getString(7));
      out.write("\" placeholder=\"Enter address\" required>\r\n");
      out.write("<h3 style=\"margin-left:650px;width: 200px;top:180px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ; padding:6px\">Enter City</h3>\r\n");
      out.write("\t<input style=\"margin-left:870px;border:2px solid;top:175px;position:absolute\" type = \"text\" name=\"city\" value=\"");
      out.print(rs2.getString(8));
      out.write("\" placeholder=\"Enter city\" required>\r\n");
      out.write("\t<h3 style=\"margin-left:150px;width: 189px;top:270px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">Enter State</h3>\r\n");
      out.write("\t<input style=\"margin-left:360px;border:2px solid;top:265px;position:absolute\" type = \"text\" name=\"state\" value=\"");
      out.print(rs2.getString(9));
      out.write("\" placeholder=\"Enter state\" required>\r\n");
      out.write("\t<h3 style=\"margin-left:650px;width: 200px;top:270px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">Enter Country</h3>\r\n");
      out.write("\t<input style=\"margin-left:870px;border:2px solid;top:265px;position:absolute\" type = \"text\" name=\"country\" value=\"");
      out.print(rs2.getString(10));
      out.write("\" placeholder=\"Enter country\" required>\r\n");
      out.write("\r\n");
      out.write("<h3 style=\"margin-left:150px;width: 189px;top:370px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">EnterPayMode</h3>\r\n");
      out.write("\t<input style=\"margin-left:360px;border:2px solid;top:365px;position:absolute\" type = \"text\" name=\"paymentmethod\" value=\"Online transaction\" placeholder=\"Enter payment method\" required>\r\n");
      out.write("\t\r\n");
      out.write("<h3 style=\"margin-left:650px;width: 200px;top:370px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">MobileNumber</h3>\r\n");
      out.write("\t<input style=\"margin-left:870px;border:2px solid;top:365px;position:absolute\" type = \"text\" name=\"mobilenumber\" value=\"");
      out.print(rs2.getString(3));
      out.write("\" placeholder=\"Enter mobile number\" required>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3 style=\"margin-left:150px;width: 450px;top:470px;position:absolute;font-size:25px;font-family: Verdana, Arial, Helvetica, sans-serif ;border:2px solid ;padding:6px\">Pay online to THE ORGANIC FARM</h3>\r\n");
      out.write("<input style=\"margin-left:660px;border:2px solid;top:465px;position:absolute\" type = \"text\" name=\"transactionid\" placeholder=\"Enter TransactionId\" required>\r\n");
      out.write("<img src=\"images/qr_code.png\" style=\"position:absolute;top:465px;margin-left:950px; width:300px\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("<h3 style=\"color: red;margin-left:150px;top:565px;position:absolute\">*Please enter your transaction ID.</h3>\r\n");
      out.write("\r\n");
      out.write("<h3 style=\"color: red;margin-left:150px;top:620px;position:absolute\">T&C* Orders may be terminated if transactionId is incorrect.</h3>\r\n");
      out.write("<button class=\"main-btn\" style=\"margin-left:150px;top:670px;position:absolute\" type=\"submit\"> Proceed to Bill</button>\r\n");
      out.write("<h3 style=\"color: red;margin-left:150px;top:750px;position:absolute\">*Please check all the details before proceeding to bill.</h3>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");

}}
catch(Exception e){
System.out.println(e);
}

      out.write("\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
