/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-03-29 15:08:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class bill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bill</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../css/responsive-style.css\">\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/cartstyle.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/yourcartcss.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\tbody {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("   \r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: 100% 110%\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    padding: 30px 40px;\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("    margin-bottom: 60px;\r\n");
      out.write("    border: none !important;\r\n");
      out.write("    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.2)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-text {\r\n");
      out.write("    color: #00BCD4\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control-label {\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input,\r\n");
      out.write("textarea,\r\n");
      out.write("button {\r\n");
      out.write("    padding: 8px 15px;\r\n");
      out.write("    border-radius: 5px !important;\r\n");
      out.write("    margin: 5px 0px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 300\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus,\r\n");
      out.write("textarea:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    border: 1px solid #00BCD4;\r\n");
      out.write("    outline-width: 0;\r\n");
      out.write("    font-weight: 400\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block {\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    cursor: pointer\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block:hover {\r\n");
      out.write("    color: #fff !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    outline-width: 0\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tfont-family: cursive;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("\t\t<nav class=\"navbar  navbar-expand-lg navigation-wrap \">\r\n");
      out.write("\t\t\t\t\t <img src=\"images/Viplogo.png\" class=\"img-fluid\" style=\"position:absolute;margin-left:20px;\">\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("\t\t\t\t <img src=\"images/organicLogo.png\" class=\"img-fluid\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                         <li><a class=\"main-btn\" href=\"continueShopping.jsp\">Continue Shopping</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"main-btn\" href=\"Logout.jsp\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<center>  <div style=\"position:absolute;top:80px;background:#00a149;color:#FFC222;padding:20px;width:100%;font-family:sans-serif;font-size:35px\">\r\n");
      out.write("  <img src=\"images/check-mark (1).png\"><br>ORDER PLACED!<br>  THANK YOU!! <br> Will be delivered in 24 hours!\r\n");
      out.write("      </div></center>\r\n");

String email=session.getAttribute("email").toString();
int total=0;
int sno=0;
try {
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/viporg", "root", "root");
	Statement st=con.createStatement();
	ResultSet rs=st.executeQuery("select sum(total) from cart where email='"+email+"'and statuss='bill'");
	while(rs.next())
	{
		total=rs.getInt(1);
		} 
	ResultSet rs2=st.executeQuery("select *from users inner join cart where cart.email='"+email+"'and cart.statuss='bill'");
	while(rs2.next())
	{ 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"card\" style=\"position:absolute;margin-left:30px;top:300px;width:95%;\">\r\n");
      out.write("<form action=\"editProductsAction.jsp\" class=\"form-card\" method=\"post\" >\r\n");
      out.write("<div class=\"row justify-content-between text-left\">\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Email<span class=\"text-danger\">*</span></label></h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:100px\">");
out.println(email); 
      out.write(" </div>\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Mobile Number<span class=\"text-danger\">*</span></label> </h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:250px\">");
      out.print(rs2.getString(20) );
      out.write("</label> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row justify-content-between text-left\">\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Payment Method<span class=\"text-danger\">*</span></label></h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:280px\">");
      out.print(rs2.getString(21) );
      out.write(" </div>\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Transaction Id<span class=\"text-danger\">*</span></label> </h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:240px\">");
      out.print(rs2.getString(22) );
      out.write("</label> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("<div class=\"row justify-content-between text-left\">\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">City<span class=\"text-danger\">*</span></label></h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:100px\">");
      out.print(rs2.getString(17) );
      out.write(" </div>\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Address<span class=\"text-danger\">*</span></label> </h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:160px\">");
      out.print(rs2.getString(16) );
      out.write("</label> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("<div class=\"row justify-content-between text-left\">\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">State<span class=\"text-danger\">*</span></label></h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:100px\">");
      out.print(rs2.getString(18) );
      out.write(" </div>\r\n");
      out.write("<div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"font-size:2rem; color:purple;\"> <label class=\"form-control-label px-3\" style=\"font-size:2rem; color:purple;\">Country<span class=\"text-danger\">*</span></label> </h4> <label class=\"form-control-label px-3\" style=\"font-size:1.8rem; position:absolute;margin-left:160px\">");
      out.print(rs2.getString(19) );
      out.write("</label> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
break;} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("<table id=\"customers\">\r\n");
      out.write("<div class=\"container\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-hover shopping-cart-wrap\" style=\"position:relative;top:790px;width:1200px;margin-left:150px\" >\r\n");
      out.write("<thead class=\"text-muted\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>S.No</th>\r\n");
      out.write("    <th>Product Name</th>\r\n");
      out.write("    <th>category</th>\r\n");
      out.write("    <th>Price</th>\r\n");
      out.write("    <th>Quantity</th>\r\n");
      out.write("     <th>Sub Total</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");

  ResultSet rs1=st.executeQuery("select *from cart inner join products where cart.productid= products.id and cart.email='"+email+"' and cart.statuss='bill'");
  while (rs1.next())
  {
	  sno=sno+1;
  
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>");
 out.println(sno); 
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs1.getString(15) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs1.getString(16) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs1.getString(17) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print(rs1.getString(3) );
      out.write("</td>\r\n");
      out.write("     <td>");
      out.print(rs1.getString(5) );
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
} 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</table>\r\n");
      out.write("<center>\r\n");
      out.write("<div style=\"position:absolute;top:620px;margin-left:555px;\">\r\n");
      out.write("<h3>Total: Rs.");
out.println(total); 
      out.write("</h3>\r\n");
      out.write("<h3>Total after 10% discount: Rs.");
out.println(total-(total/10)); 
      out.write("/-</h3>\r\n");
      out.write("\r\n");
      out.write("<a onclick=\"window.print();\"><button class=\"main-btn\">Print</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("<br><br><br><br>\r\n");

}
catch(Exception e){
System.out.println(e);
}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
