/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-03-08 21:42:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <meta name=\"Description\" content=\"Enter your description here\" />\r\n");
      out.write("  <title>100% Organic</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("  <!-- bootstrap CDN -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- OWN CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/responsive-style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-bs-spy=\"scroll\" data-bs-target=\".navbar\" data-bs-offset=\"100\">\r\n");
String email=session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("  <!-- header design -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navigation-wrap\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("          <img src=\"./images/organicLogo.png\" class=\"img-fluid\" style=\"position:absolute;margin-left:550px;\">\r\n");
      out.write("          <img src=\"./images/Viplogo.png\" class=\"img-fluid\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n");
      out.write("          <i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("          <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"homepage.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"myCart.jsp\">My Cart</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"myOrders.jsp\">My Orders</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"Logout.jsp\">Logout</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#\"><h3 style=\"font-size:1.5rem; color:#380556;\"> ");
out.println(email);
      out.write("</h3></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- section-1 top-banner -->\r\n");
      out.write("  <section id=\"home\">\r\n");
      out.write("    <div class=\"container-fluid px-0 top-banner\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-5 col-md-6\">\r\n");
      out.write("            <h1>FARM FRESH ORGANIC <br><span> Everything Available Here!</span></h1>\r\n");
      out.write("            <h2>Enjoy Free Home Delivery In Hyderabad</h2>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-4\">\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- section-2 our-menu -->\r\n");
      out.write("  <section class=\"our-menu p-4\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <h2 class=\"pb-4\">Our Products</h2>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"prodfruits.jsp\">\r\n");
      out.write("                <img src=\"./images/img/fruits.png\"  class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"prodfruits.jsp\">Fruits</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"prodvege.jsp\">\r\n");
      out.write("                <img src=\"./images/img/vegetable.png\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"prodvege.jsp\">Vegetables</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"prodgrains.jsp\">\r\n");
      out.write("                <img src=\"./images/img/wheat-sack (1).png\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"prodgrains.jsp\">Grains</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"proddry.jsp\">\r\n");
      out.write("                <img src=\"./images/img/nuts (1).png\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"proddry.jsp\">Organic Dry Fruits</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"prodoil.jsp\">\r\n");
      out.write("                <img src=\"./images/img/olive-oil (1).png\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"prodoil.jsp\">Oils</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 col-sm-2 mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"cat-image\">\r\n");
      out.write("              <a class=\"link_category_product\" href=\"prodspices.jsp\">\r\n");
      out.write("                <img src=\"./images/img/spicy-food (1).png\" class=\"img-fluid\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cat-title\">\r\n");
      out.write("              <a href=\"prodspices.jsp\">Spices</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- section-3 about-->\r\n");
      out.write("  <section id=\"about\">\r\n");
      out.write("    <div class=\"about-section wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-7 col-md-12 mb-lg-0 mb-5\">\r\n");
      out.write("            <div class=\"card border-0\">\r\n");
      out.write("              <img src=\"./images/img/img-1.PNG\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-5 col-md-12 text-sec\">\r\n");
      out.write("            <h2>Straight From The Earth To Your Plate.</h2>\r\n");
      out.write("            <p>Now delivering Fresh Produce across<h1> <span>Hyderabad</span></h1></p>\r\n");
      out.write("            <button class=\"main-btn mt-4\" onclick=\"document.getElementById('id01').style.display='block'\">Learn More</button>\r\n");
      out.write("            <div id=\"id01\" class=\"w3-modal\"  >\r\n");
      out.write("              <div class=\"w3-modal-content w3-animate-top w3-card-4\" id=\"header\">\r\n");
      out.write("                <header class=\"w3-container w3-teal\" >\r\n");
      out.write("                  <span onclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("                  class=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("                  <h2>Delivering across Hyderabad</h2>\r\n");
      out.write("                </header>\r\n");
      out.write("                <div class=\"w3-container\">\r\n");
      out.write("                  <h1 style=\"color:green ;font-family:calibri; font-size:2.2rem;  text-shadow: 1px 0 0px #FFC222;\">Enjoy free home delivery in Hyderabad</h1>\r\n");
      out.write("                  <h3 style=\"color:black ;font-style:Source Sans Pro; font-size:1.7rem;\">On order values above Rs.300</h3>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li id=\"l1\" style=\"font-size:1.3rem;font-style:calibri;list-style-image: url(C:/Sublime/fv.png);list-style-position: inside;\">Organic Fruits and Vegetables </li>\r\n");
      out.write("                    <li id=\"l1\" style=\"font-size:1.3rem;font-style:calibri;list-style-image: url(C:/Sublime/hand.png);list-style-position: inside;\">Organic staples </li>\r\n");
      out.write("                    <li id=\"l1\" style=\"font-size:1.3rem;font-style:calibri;list-style-image: url(C:/Sublime/healthcare.png);list-style-position: inside;\">Health & Wellness </li>\r\n");
      out.write("                    <li id=\"l1\" style=\"font-size:1.3rem;font-style:calibri;list-style-image: url(C:/Sublime/beverage.png);list-style-position: inside;\">Snacks & Beverages</li>\r\n");
      out.write("                    <li id=\"l1\" style=\"font-size:1.3rem;font-style:calibri;list-style-image: url(C:/Sublime/home.png);list-style-position: inside;\">Home & Living </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container food-type\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-5 col-md-12 text-sec mb-lg-0 mb-5\">\r\n");
      out.write("            <h2>Good Things Comes In Wholesome Packages</h2>\r\n");
      out.write("            <p>Curated organic fruit baskets & veggie Baskets</p>\r\n");
      out.write("            <ul class=\"list-unstyled py-3\">\r\n");
      out.write("              <li>Fruit Basket @399/-</li>\r\n");
      out.write("              <li>Veggie Basket @639/-.</li>\r\n");
      out.write("              <li>Fruit + Veggie Basket @950/-</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <button class=\"main-btn mt-4\" onclick=\"document.getElementById('id02').style.display='block'\">Learn More</button>\r\n");
      out.write("            <div id=\"id02\" class=\"w3-modal\"  >\r\n");
      out.write("              <div class=\"w3-modal-content w3-animate-top w3-card-4\" id=\"header\">\r\n");
      out.write("                <header class=\"w3-container w3-teal\" >\r\n");
      out.write("                  <span onclick=\"document.getElementById('id02').style.display='none'\"\r\n");
      out.write("                  class=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("                  <h2>Combos</h2>\r\n");
      out.write("                </header>\r\n");
      out.write("                <div class=\"w3-container\">\r\n");
      out.write("                  <h3 style=\"color:black ;font-style:Source Sans Pro; font-size:1.7rem;\">Buy these Fruits & Vegetable combos designed for your convenience and regular top-ups.</h3>\r\n");
      out.write("                  <h2 style=\"color:green;\">Festive Combo 1</h2>\r\n");
      out.write("                  <h5>Apple Shimla(4Pcs), Banana Robusta(500gm), Sweetlime(500gm), Pineapple(1pc) and Guava(500gm)</h5>\r\n");
      out.write("                  <h2 style=\"color:green;\">Festive Combo 2</h2>\r\n");
      out.write("                  <h5>Apple Shimla(4Pcs), Banana Yelakki(500gm), Sweetlime(500gm), Guava(500gm) and Pomegranate(500gm).</h5>\r\n");
      out.write("                  <h2 style=\"color:green;\">POT Combo</h2>\r\n");
      out.write("                  <h5>Potato(1kg), Onion(1kg) and Tomato Hybrid(1kg)</h5>\r\n");
      out.write("                  <h2 style=\"color:green;\">Indian Greens Combo</h2>\r\n");
      out.write("                  <h5>Spinach(150 gm), Coriander(100 gm), Methi(150gm), Green or Red Amaranthus(200 gm) and Mint(100gm)</h5>\r\n");
      out.write("\r\n");
      out.write("                  <h2 style=\"color:green;\">Value Add Combo</h2>\r\n");
      out.write("                  <h5>Potato,Onion(1kg each),Tomato,Bottlegourd, Ladies Finger(500gm each), Coriander(100gm), Spinach(150gm), Ginger,Garlic,Lemon,Green</h5>\r\n");
      out.write("                  <h2 style=\"color:green;\">Chutney Combo</h2>\r\n");
      out.write("                  <h5>Coriander(100gm), Green Chilli(250gm), Ginger(250gm), Coconut(1pc) and Garlic(250gm)</h5>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"col-lg-7 col-md-12\">\r\n");
      out.write("            <div class=\"card border-0\">\r\n");
      out.write("              <img src=\"./images/img/img-2.png\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- section-4 explore food-->\r\n");
      out.write("  <section id=\"explore-food\">\r\n");
      out.write("    <div class=\"explore-food wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-12\">\r\n");
      out.write("            <div class=\"text-content text-center\">\r\n");
      out.write("              <h1><span>Blog</span></h1>\r\n");
      out.write("              <p>The choices we make matter.\r\n");
      out.write("\r\n");
      out.write("100%ORGANIC looks to provide people with a healthier and more sustainable approach to life.\r\n");
      out.write(" We aim to be on the frontlines of the revolution for a healthier living. Our brand was conceptualised\r\n");
      out.write("  keeping purity and quality at the heart of everything we do.\r\n");
      out.write("  We aim to revitalise sustainable agricultural practices in India by collaborating directly\r\n");
      out.write("  with the farmers and making natural and healthier food more accessible to all.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row pt-5\">\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-lg-0 mb-5\">\r\n");
      out.write("            <div class=\"card border\">\r\n");
      out.write("              <img src=\"./images/img/img-3.PNG\" class=\"img-fluid\">\r\n");
      out.write("              <div class=\"p-3\">\r\n");
      out.write("                <h5>Choose Better</h5>\r\n");
      out.write("                <p>New Year is just around the corner and people are going to set their resolutions, yet again. On top of that list is most likely going to be health and everything around it.  People will seem motivated and will expect this year to be different...\r\n");
      out.write("By 100% ORGANIC</p>\r\n");
      out.write("                <button onclick=\"window.location='R1.html';\" class=\"mt-2 main-btn\">Read More</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-lg-0 mb-5\">\r\n");
      out.write("            <div class=\"card border\">\r\n");
      out.write("              <img src=\"./images/img/img-4.PNG\" class=\"img-fluid\">\r\n");
      out.write("              <div class=\"p-3\">\r\n");
      out.write("                <h5>Organic jaggery powder benefits and uses</h5>\r\n");
      out.write("                <p>Jaggery is not just a natural sweetener for Indians. These orange blocks of sweetness have been part of our culture since ages. You will find Jaggery in every kitchen waiting to be taken out to be used in traditional sweets...\r\n");
      out.write("By 100% ORGANIC</p>\r\n");
      out.write("                <button onclick=\"window.location='r2.html';\" class=\"mt-2 main-btn\">Read More</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 mb-lg-0 mb-5\">\r\n");
      out.write("            <div class=\"card border\">\r\n");
      out.write("              <img src=\"./images/img/img-5.PNG\" class=\"img-fluid\">\r\n");
      out.write("              <div class=\"p-3\">\r\n");
      out.write("                <h5>Quick & Delicious Winter Veggie Soup</h5>\r\n");
      out.write("                <p>As the winter months set in, itâs common to crave for comfort food and find yourself indulging in some not-so-healthy but oh-so-delicious meals. From mugs of piping hot chocolate to a spicy bowl of ramen, winter food is definitely enjoyable...\r\n");
      out.write("By 100% ORGANIC</p>\r\n");
      out.write("                <button onclick=\"window.location='r3.html';\"class=\"mt-2 main-btn\">Read More</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Section-5 testimonial-->\r\n");
      out.write("  <section id=\"testimonial\">\r\n");
      out.write("    <div class=\"wrapper testimonial-section\">\r\n");
      out.write("      <div class=\"container text-center\">\r\n");
      out.write("        <div class=\"text-center pb-4\">\r\n");
      out.write("          <h1>Reviews</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("            <div id=\"carouselExampleDark\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("              <div class=\"carousel-indicators\">\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleDark\" data-bs-slide-to=\"0\" class=\"active\"\r\n");
      out.write("                  aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleDark\" data-bs-slide-to=\"1\"\r\n");
      out.write("                  aria-label=\"Slide 2\"></button>\r\n");
      out.write("                <button type=\"button\" data-bs-target=\"#carouselExampleDark\" data-bs-slide-to=\"2\"\r\n");
      out.write("                  aria-label=\"Slide 3\"></button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                    <img src=\"./images/review/boy (1).png\">\r\n");
      out.write("                    <p>\"I am a resident of Villa Greens and I am sending this message as I truly appreciate good quality fruits and vegetables being supplied by you especially in the current situation. The taste of the fruits and vegetables is very good. Wanted to say thank you.   A big thank you ð. Thank you for your excellent service. \"</p>\r\n");
      out.write("                    <h5>Arjun-Designer</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                    <img src=\"./images/review/girl (1).png\">\r\n");
      out.write("                    <p>\"Fresh and good quality organic produce and grocery, prompt service. Kudos to the management and the team of TG. ðð\r\n");
      out.write("\r\n");
      out.write("Laxmi has been a loyal customer of 100% ORGANIC since its inception and enjoys the flexibility of ordering her groceries and essentials via phone. \"</p>\r\n");
      out.write("                    <h5>Laxmi - Front End</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                  <div class=\"carousel-caption\">\r\n");
      out.write("                    <img src=\"images/review/aunt (1).png\">\r\n");
      out.write("                    <p>\"I truly appreciate good quality fruits and vegetables being supplied by you especially in the current situation. The taste of the fruits and vegetables is very good. Wanted to say thank you. \"</p>\r\n");
      out.write("                    <h5>Ramu - UX Designer</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- section-6 footer-->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer pt-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 text-center\">\r\n");
      out.write("            <div class=\"footer-social pb-4 text-center\">\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-dribbble\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <form class=\"newsletter\">\r\n");
      out.write("              <div class=\"d-flex\">\r\n");
      out.write("                <input class=\"form-control\" placeholder=\"Email Address Here\" type=\"email\" style=\"color:white\">\r\n");
      out.write("                <button class=\"main-btn\" type=\"submit\" >Subscribe</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-sm-12\">\r\n");
      out.write("            <div class=\"footer-copy\">\r\n");
      out.write("              <div class=\"copy-right text-center pt-5\">\r\n");
      out.write("                <p class=\"text-light\">Â© 2021. 100%ORGANIC. All rights reserved.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a href=\"#home\" class=\"main-btn1\">\r\n");
      out.write("                    /|\\</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- JS Libraries -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- own js -->\r\n");
      out.write("  <script src=\"./js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
