/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-03-10 14:50:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>Register</title>\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/responsive-style.css\">\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script >\r\n");
      out.write("\t\tfunction validate(val) {\r\n");
      out.write("v1 = document.getElementById(\"name\");\r\n");
      out.write("v2 = document.getElementById(\"mobilenumber\");\r\n");
      out.write("v3 = document.getElementById(\"email\");\r\n");
      out.write("v4 = document.getElementById(\"password\");\r\n");
      out.write("v5 = document.getElementById(\"answer\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("flag1 = true;\r\n");
      out.write("flag2 = true;\r\n");
      out.write("flag3 = true;\r\n");
      out.write("flag4 = true;\r\n");
      out.write("flag5 = true;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(val>=1 || val==0) {\r\n");
      out.write("if(v1.value == \"\") {\r\n");
      out.write("v1.style.borderColor = \"red\";\r\n");
      out.write("flag1 = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("v1.style.borderColor = \"green\";\r\n");
      out.write("flag1 = true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(val>=2 || val==0) {\r\n");
      out.write("if(v2.value == \"\") {\r\n");
      out.write("v2.style.borderColor = \"red\";\r\n");
      out.write("flag2 = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("v2.style.borderColor = \"green\";\r\n");
      out.write("flag2 = true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("if(val>=3 || val==0) {\r\n");
      out.write("if(v3.value == \"\") {\r\n");
      out.write("v3.style.borderColor = \"red\";\r\n");
      out.write("flag3 = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("v3.style.borderColor = \"green\";\r\n");
      out.write("flag3 = true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("if(val>=4 || val==0) {\r\n");
      out.write("if(v4.value == \"\") {\r\n");
      out.write("v4.style.borderColor = \"red\";\r\n");
      out.write("flag4 = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("v4.style.borderColor = \"green\";\r\n");
      out.write("flag4 = true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("if(val>=5 || val==0) {\r\n");
      out.write("if(v5.value == \"\") {\r\n");
      out.write("v5.style.borderColor = \"red\";\r\n");
      out.write("flag5 = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write("v5.style.borderColor = \"green\";\r\n");
      out.write("flag5 = true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("flag = flag1 && flag2 && flag3 && flag4 && flag5;\r\n");
      out.write("\r\n");
      out.write("return flag;\r\n");
      out.write("}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-image: url(\"https://i.imgur.com/GMmCQHC.png\");\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: 100% 100%\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    padding: 30px 40px;\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("    margin-bottom: 60px;\r\n");
      out.write("    border: none !important;\r\n");
      out.write("    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.2)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blue-text {\r\n");
      out.write("    color: #00BCD4\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control-label {\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input,\r\n");
      out.write("textarea,\r\n");
      out.write("button {\r\n");
      out.write("    padding: 8px 15px;\r\n");
      out.write("    border-radius: 5px !important;\r\n");
      out.write("    margin: 5px 0px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 300\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus,\r\n");
      out.write("textarea:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    border: 1px solid #00BCD4;\r\n");
      out.write("    outline-width: 0;\r\n");
      out.write("    font-weight: 400\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block {\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 18px !important;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    height: 43px;\r\n");
      out.write("    cursor: pointer\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block:hover {\r\n");
      out.write("    color: #fff !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:focus {\r\n");
      out.write("    -moz-box-shadow: none !important;\r\n");
      out.write("    -webkit-box-shadow: none !important;\r\n");
      out.write("    box-shadow: none !important;\r\n");
      out.write("    outline-width: 0\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tfont-family: cursive;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav class=\"navbar  navbar-expand-lg navigation-wrap \">\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\" >\r\n");
      out.write("\t\t\t\t\t\t<a class=\"main-btn\" href=\"firstpage.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t    <img src=\"./images/Viplogo.png\" class=\"img-fluid\" style=\"position:absolute;margin-left:610px;\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("\t\t\t\t <img src=\"./images/organicLogo.png\" class=\"img-fluid\" style=\"margin-left:1060px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("<div class=\"container-fluid px-1 py-5 mx-auto\">\r\n");
      out.write("    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"col-xl-7 col-lg-8 col-md-9 col-11 text-center\">\r\n");
      out.write("            <h1>REGISTER</h1>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("                <form class=\"form-card\" action=\"signupAction.jsp\" method=\"post\">\r\n");
      out.write("                    <div class=\"row justify-content-between text-left\">\r\n");
      out.write("                        <div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"color:black\"> <label class=\"form-control-label px-3\">Name<span class=\"text-danger\"> *</span></label></h4> <input type=\"text\" name=\"name\" placeholder=\"Enter your name\" onblur=\"validate(1)\" required> </div>\r\n");
      out.write("                        <div class=\"form-group col-sm-6 flex-column d-flex\"><h4 style=\"color:black\"> <label class=\"form-control-label px-3\">Mobile Number<span class=\"text-danger\"> *</span></label> </h4><input type=\"number\" name=\"mobilenumber\" placeholder=\"Enter your Mobile number\" onblur=\"validate(2)\"> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row justify-content-between text-left\">\r\n");
      out.write("                        <div class=\"form-group col-sm-6 flex-column d-flex\"> <h4 style=\"color:black\"><label class=\"form-control-label px-3\"> Email<span class=\"text-danger\"> *</span></label> </h4><input type=\"email\" name=\"email\" placeholder=\"Enter Email\" onblur=\"validate(3)\" required> </div>\r\n");
      out.write("                        <div class=\"form-group col-sm-6 flex-column d-flex\"> <h4 style=\"color:black\"><label class=\"form-control-label px-3\">Password<span class=\"text-danger\"> *</span></label> </h4><input type=\"password\" name=\"password\" placeholder=\"Enter Password\" onblur=\"validate(4)\" required> </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<center>\t<div class=\"row justify-content-center\">\r\n");
      out.write("                        <div class=\"form-group col-sm-6 flex-column d-flex\"> <h4 style=\"color:black\"><select name=\"securityQuestion\" style=\"width:70%\" required>\r\n");
      out.write("\t  <option value=\"Where were you born?\">Where were you Born?</option>\r\n");
      out.write("\t  <option value=\"What is your favourite colour?\">What is your favourite color?</option>\r\n");
      out.write("\t  <option value=\"Who is your bestfriend?\">Who is your Best Friend?</option>\r\n");
      out.write("\t </select> <span class=\"text-danger\"> *</span><br></td></tr>  </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-sm-6 flex-column d-flex\"> <h4 style=\"color:black\"></label> </h4><input type=\"text\" name=\"answer\" placeholder=\"Enter Answer\" onblur=\"validate(5)\" required> </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row justify-content-center\">\r\n");
      out.write("                        <div class=\"form-group col-sm-6\"><input type=\"submit\" class=\"btn-block btn-success\" value=\"signup\"> </div>\r\n");
      out.write("                        <h4>Already have an account?<a href=\"login.jsp\"> Login</a></h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  ");

  String msg=request.getParameter("msg");
  if("valid".equals(msg))
  {
  
      out.write("\r\n");
      out.write("<h1 style=\"position:absolute;top: 180px; margin-left:520px\">Successfully Registered !</h1>\r\n");
}
      out.write(' ');
      out.write('\r');
      out.write('\n');

if ("invalid".equals(msg))
{
	 
      out.write("\r\n");
      out.write("<h1 style=\"position:absolute;top: 180px; margin-left:520px\">Error occured. Please try again.</h1>\r\n");
}
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
