/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2023-08-05 06:05:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class ordersReceived_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/adminHeader.jsp", Long.valueOf(1619847601869L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("    <!--Header-->\r\n");
      out.write("   \r\n");
      out.write("   ");
String email= session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("            <center><h2>THE CAM STORE </h2></center>\r\n");
      out.write("            <a href=\"allProductEditProduct.jsp\">Edit Products </a><br>\r\n");
      out.write("            <a href=\"ordersReceived.jsp\">Orders Received </a><br>\r\n");
      out.write("            <a href=\"../Logout.jsp\">Logout </a><br>\r\n");
      out.write("         \r\n");
      out.write("           <br>\r\n");
      out.write("           <!--table-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#99C68E\">\r\n");
      out.write(" <h3>Orders Received</h3>\r\n");

String msg=request.getParameter("msg");

if("cancel".equals(msg))
		{
	
      out.write("\r\n");
      out.write("<h3 >Order is Cancelled!</h3>\r\n");
}
      out.write('\r');
      out.write('\n');

if("delivered".equals(msg))
		{
      out.write("\r\n");
      out.write("<h3>Order is delivered!</h3>\r\n");
}
      out.write('\r');
      out.write('\n');

if("invalid".equals(msg))
		{
      out.write("\r\n");
      out.write("<h3 >Error occured! Please try again!</h3>\r\n");
}
      out.write('\r');
      out.write('\n');

int total=0;
try {
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shalu", "root", "root");
	Statement st=con.createStatement();
	ResultSet rs1=st.executeQuery("select sum(total) from cart where statuss='delivered'");
	while(rs1.next())
	{
		total=rs1.getInt(1);
	} 
	
      out.write("\r\n");
      out.write("<table id=\"customers\">\r\n");
      out.write("          <tr>\r\n");
      out.write("           <th scope=\"col\" style=\"background-color:#FFE6BB ;\">Account balance:  ");
out.println(total-(total/10)); 
      out.write("  </th>\r\n");
      out.write("          <th scope=\"col\">sno</th>\r\n");
      out.write("          <th scope=\"col\">Email</th>\r\n");
      out.write("          <th scope=\"col\">Mobile Number</th>\r\n");
      out.write("            <th scope=\"col\">Product Name</th>\r\n");
      out.write("            <th scope=\"col\">Quantity</th>\r\n");
      out.write("            <th scope=\"col\"> Sub Total</th>\r\n");
      out.write("            <th scope=\"col\">Address</th>\r\n");
      out.write("            <th scope=\"col\">City</th>\r\n");
      out.write("            <th scope=\"col\">State</th>\r\n");
      out.write("            <th scope=\"col\">Country</th>\r\n");
      out.write("             <th scope=\"col\">Payment Method</th>\r\n");
      out.write("              <th scope=\"col\">T-ID</th>\r\n");
      out.write("              <th scope=\"col\">Status</th>\r\n");
      out.write("              <th scope=\"col\">Action</th>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");

		}
catch(Exception e)
		{
	System.out.println(e);
		}

      out.write("\r\n");
      out.write("          \r\n");
      out.write("      ");

      
      int sno=0;
		try{
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shalu", "root", "root");
			Statement st=con.createStatement();
			ResultSet rs=st.executeQuery("select *from cart inner join products where cart.productid=products.id and cart.transactionid is not NULL and cart.statuss='processing'");
			while(rs.next())
			{
				sno=sno+1;
			
      out.write("  \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("         \r\n");
      out.write("          <tr>\r\n");
      out.write("          \r\n");
      out.write("          <td>");
 out.println(sno); 
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(rs.getString(10) );
      out.write("</td>\r\n");
      out.write("            <td> ");
      out.print(rs.getString(15) );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(rs.getString(3) );
      out.write(" </td>\r\n");
      out.write("             <td>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("               <td> ");
      out.print(rs.getString(8) );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(rs.getString(9) );
      out.write(" </td>\r\n");
      out.write("             <td>");
      out.print(rs.getString(11) );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print(rs.getString(12) );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(rs.getString(13) );
      out.write("</td>\r\n");
      out.write("            \r\n");
      out.write("      \r\n");
      out.write("               <td><a href=\"cancelordersAction.jsp?id=");
      out.print(rs.getString(2));
      out.write("&email=");
      out.print(rs.getString(1));
      out.write("\">Cancel </a></td>\r\n");
      out.write("                <td><a href=\"deliveredordersAction.jsp?id=");
      out.print(rs.getString(2));
      out.write("&email=");
      out.print(rs.getString(1));
      out.write("\">Deliver </a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    \r\n");

		}
catch(Exception e)
		{
	System.out.println(e);
		}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
