/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-03-29 14:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.finalVIP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <meta name=\"Description\" content=\"Enter your description here\" />\r\n");
      out.write("  <title>VIP Main Page</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- bootstrap CDN -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- OWN CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"images/css/style1.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/responsive-style.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("  .mySlides {display: none;}\r\n");
      out.write("  img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("  /* Slideshow container */\r\n");
      out.write("  .slideshow-container {\r\n");
      out.write("    top:110px;\r\n");
      out.write("    max-width:100%;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    margin-left:0px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* The dots/bullets/indicators */\r\n");
      out.write("  .dot {\r\n");
      out.write("    height: 15px;\r\n");
      out.write("    width: 15px;\r\n");
      out.write("    margin: 0 2px;\r\n");
      out.write("    background-color: #bbb;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    transition: background-color 0.6s ease;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .active {\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* Fading animation */\r\n");
      out.write("  .fade {\r\n");
      out.write("    -webkit-animation-name: fade;\r\n");
      out.write("    -webkit-animation-duration: 1.5s;\r\n");
      out.write("    animation-name: fade;\r\n");
      out.write("    animation-duration: 1.5s;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @-webkit-keyframes fade {\r\n");
      out.write("    from {opacity: .4}\r\n");
      out.write("    to {opacity: 1}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @keyframes fade {\r\n");
      out.write("    from {opacity: .4}\r\n");
      out.write("    to {opacity: 1}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* On smaller screens, decrease text size */\r\n");
      out.write("  @media only screen and (max-width: 300px) {\r\n");
      out.write("    .text {font-size: 11px}\r\n");
      out.write("  }\r\n");
      out.write("  input[type=text] {\r\n");
      out.write("  margin-left:300px;\r\n");
      out.write("  width: 450px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border: 2px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  background-image: url('images/search.png');\r\n");
      out.write("  background-position: 10px 10px;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  padding: 12px 20px 12px 40px;\r\n");
      out.write("  -webkit-transition: width 0.4s ease-in-out;\r\n");
      out.write("  transition: width 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]:focus {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".dropdown {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  margin-left: 330px;\r\n");
      out.write("  margin-top: 100px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  min-width: 160px;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("  color: black;\r\n");
      out.write("  padding: 12px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {background-color: #ddd}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover, .dropdown:hover .btn {\r\n");
      out.write("  background-color: #0b7dda;\r\n");
      out.write("}\r\n");
      out.write(".sidebar {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top:105px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a {\r\n");
      out.write("  padding: 8px 8px 8px 32px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 25px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".openbtn {\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:15px;\r\n");
      out.write("  margin-left:-100px;\r\n");
      out.write("  font-size: 35px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  background-color:#472780;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".openbtn:hover {\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("  transition: margin-left .5s;\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */\r\n");
      out.write("@media screen and (max-height: 450px) {\r\n");
      out.write("  .sidebar {padding-top: 15px;}\r\n");
      out.write("  .sidebar a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write(" /*\r\n");
      out.write("==========================================\r\n");
      out.write("footer section Design\r\n");
      out.write("==========================================\r\n");
      out.write("*/\r\n");
      out.write(".footer{\r\n");
      out.write("  background: #472780;\r\n");
      out.write("  bottom:50%;\r\n");
      out.write("}\r\n");
      out.write(".footer .footer-link{\r\n");
      out.write("  font-size:1rem;\r\n");
      out.write("  color:var(--white-color);\r\n");
      out.write("  padding:0 1.875rem;\r\n");
      out.write("}\r\n");
      out.write(".footer .footer-link:hover{\r\n");
      out.write("  color:var(--white-color) !important;\r\n");
      out.write("}\r\n");
      out.write(".footer a i{\r\n");
      out.write("  font-size: 1.5rem;\r\n");
      out.write("  color:var(--white-color);\r\n");
      out.write("  padding:0 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media (max-width:1024px)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("    /* about section */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 991px)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("    /*custom classes  */\r\n");
      out.write("    .text-content{\r\n");
      out.write("        width:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* navbar brand */\r\n");
      out.write("    .navigation-wrap .navbar-brand img{\r\n");
      out.write("        height:3.8125rem;\r\n");
      out.write("    }\r\n");
      out.write("    .navigation-wrap{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        background-color: var(--white-color);\r\n");
      out.write("    }\r\n");
      out.write("    .navigation-wrap .nav-link{\r\n");
      out.write("        line-height: 1.875rem;\r\n");
      out.write("    }\r\n");
      out.write("    /* Banner Design */\r\n");
      out.write("    .top-banner{\r\n");
      out.write("        padding:9.375rem 0 9.375rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* carousel design */\r\n");
      out.write("    .testimonial-section .carousel-item .carousel-caption p{\r\n");
      out.write("        padding:0;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("document.getElementById(\"mySidebar\").style.width = \"250px\";\r\n");
      out.write("document.getElementById(\"slide\").style.marginLeft = \"300px\";\r\n");
      out.write("document.getElementById(\"doc\").style.marginLeft = \"300px\";\r\n");
      out.write("document.getElementById(\"cat\").style.marginLeft = \"300px\";\r\n");
      out.write("document.getElementById(\"organic\").style.marginLeft = \"300px\";\r\n");
      out.write("document.getElementById(\"organic1\").style.marginLeft = \"300px\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeNav() {\r\n");
      out.write("\tdocument.getElementById(\"mySidebar\").style.width = \"0\";\r\n");
      out.write("\tdocument.getElementById(\"slide\").style.marginLeft= \"300px\";\r\n");
      out.write("\tdocument.getElementById(\"doc\").style.marginLeft= \"300px\";\r\n");
      out.write("\tdocument.getElementById(\"cat\").style.marginLeft= \"300px\";\r\n");
      out.write("\tdocument.getElementById(\"organic\").style.marginLeft= \"300px\";\r\n");
      out.write("\tdocument.getElementById(\"organic1\").style.marginLeft= \"300px\";\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("    <body data-bs-spy=\"scroll\" data-bs-target=\".navbar\" data-bs-offset=\"100\" style=\"background-color:#FBF8FF;\">\r\n");
      out.write("    ");
String email=session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("      <!-- header design -->\r\n");
      out.write("      <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navigation-wrap\" style=\"background:#472780;top:0px;\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("              <div id=\"mySidebar\" class=\"sidebar\" style= \"border-radius: 0.5rem;box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%);\">\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">x</a>\r\n");
      out.write("  <a href=\"#\"><img src=\"images/user1.png\">&nbsp &nbsp  My Profile</a><br>\r\n");
      out.write("  <a href=\"Help.html\"><img src=\"images/male-telemarketer.png\">&nbsp &nbsp  Help & Support</a><br>\r\n");
      out.write("  <a href=\"about.html\"><img src=\"images/information-button.png\">&nbsp &nbsp Terms Applied</a><br>\r\n");
      out.write("  <a href=\"logoutvip.jsp\"><img src=\"images/logout1.png\">&nbsp &nbsp  Logout</a><br>\r\n");
      out.write("</div>\r\n");
      out.write("              <div id=\"main\">\r\n");
      out.write("  <button class=\"openbtn\" onclick=\"openNav()\">=</button>  </div>\r\n");
      out.write("              <a href=\"#\"><img src=\"images/vip.png\" class=\"img-fluid\"></a>\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n");
      out.write("              <i class=\"fas fa-stream navbar-toggler-icon\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("              <form>\r\n");
      out.write("  <input type=\"text\" name=\"search\" placeholder=\"Search..\">\r\n");
      out.write("</form>\r\n");
      out.write("<div  style=\"position:absolute;margin-left:750px;top:0px;\">\r\n");
      out.write("<button class=\"main-btn\" style=\"position:absolute;margin-left:260px;top:29px;width:250px;height:50px;\">");
out.println(email);
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("      </header>\r\n");
      out.write("    <section id=\"slide\" style=\"margin-left:280px;\">\r\n");
      out.write("        <div class=\"slideshow-container\" style=\" border-radius: 0.5rem;box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%)\">\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("          <img src=\"images\\s4.jpg\" style=\"width:100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("\r\n");
      out.write("          <img src=\"images\\s5.jpg\" style=\"width:100%\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mySlides fade\" >\r\n");
      out.write("\r\n");
      out.write("          <img src=\"images\\s3.jpg\" style=\"width:100%\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"text-align:center\">\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        var slideIndex = 0;\r\n");
      out.write("        showSlides();\r\n");
      out.write("\r\n");
      out.write("        function showSlides() {\r\n");
      out.write("          var i;\r\n");
      out.write("          var slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("          var dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("          for (i = 0; i < slides.length; i++) {\r\n");
      out.write("            slides[i].style.display = \"none\";\r\n");
      out.write("          }\r\n");
      out.write("          slideIndex++;\r\n");
      out.write("          if (slideIndex > slides.length) {slideIndex = 1}\r\n");
      out.write("          for (i = 0; i < dots.length; i++) {\r\n");
      out.write("            dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("          }\r\n");
      out.write("          slides[slideIndex-1].style.display = \"block\";\r\n");
      out.write("          dots[slideIndex-1].className += \" active\";\r\n");
      out.write("          setTimeout(showSlides, 2000); // Change image every 2 seconds\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("      </section >\r\n");
      out.write("      <section id=\"doc\" style=\"margin-left:280px;\">\r\n");
      out.write("        <h4 style=\"position:absolute;top:465px;\">My Documents (From Digilocker)</h4>\r\n");
      out.write("        <div style=\"position:absolute;top:525px;width:1000px;height:100px;border-radius: 0.5rem;background-color:white; box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%); \" >\r\n");
      out.write("                  <img src=\"images/vip.png\" style=\"position:absolute;margin-left:25px;top:4px;\"class=\"img-fluid\"><a href=\"../Image-Uploader-master/Index.html\"><button class=\"main-btn\" style=\"position:absolute;margin-left:700px;top:29px;width:250px;height:50px;\"><img src=\"images/enter.png\" style=\"position:absolute;margin-left:130px;top:5px;\">Click To Upload</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("    </section >\r\n");
      out.write("    <section id=\"cat\" style=\"margin-left:280px;\">\r\n");
      out.write("      <h4 style=\"position:absolute;top:650px;\">Category</h4>\r\n");
      out.write("      <div style=\"position:absolute;top:700px;width:1000px;height:460px;border-radius: 0.5rem;background-color:white; box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%); \" >\r\n");
      out.write("    <a href=\"health_schemes.html\"><img src=\"images\\health-care.png\" style=\"position:absolute;margin-left:100px;top:30px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:130px;top:180px;\">Health</h5>\r\n");
      out.write("        <a href=\"education_scheme.html\"><img src=\"images\\open-book.png\" style=\"position:absolute;margin-left:400px;top:30px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:417px;top:180px;\">Education</h5>\r\n");
      out.write("      <a href=\"women&children_scheme.html\">  <img src=\"images\\mother-and-son-silhouettes.png\" style=\"position:absolute;margin-left:700px;top:30px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:690px;top:180px;\">Women & Children</h5>\r\n");
      out.write("      <a href=\"Youthskillsschemes.html\">  <img src=\"images\\skill.png\" style=\"position:absolute;margin-left:100px;top:260px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:40px;top:420px;\">Youth. Skills and Employment</h5>\r\n");
      out.write("      <a href=\"farmerschemes.html\">  <img src=\"images\\farmer.png\" style=\"position:absolute;margin-left:400px;top:260px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:428px;top:420px;\">Farmers</h5>\r\n");
      out.write("      <a href=\"utilitiesschemes.html\">  <img src=\"images\\maintenance.png\" style=\"position:absolute;margin-left:700px;top:260px;\"></a>\r\n");
      out.write("      <h5 style=\"position:absolute;margin-left:735px;top:420px;\">Utility</h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"organic\" style=\"margin-left:280px;\">\r\n");
      out.write("    <a href=\"../firstpage.jsp\"> <div class=\"organic\" style=\" border-radius: 0.5rem;box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%); background:url(./images/bg7.jpeg); background-repeat: no-repeat;background-size: 1200px 500px;\">\r\n");
      out.write("       <div class=\"container book-salon-text\">\r\n");
      out.write("         <div class=\"row text-center\">\r\n");
      out.write("           <div class=\"col-lg-9 col-md-12\">\r\n");
      out.write("             <img src=\"images/organicLogo.png\" class=\"img-fluid\" style=\"border-radius: 0.5rem;box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%);margin-left:550px\">\r\n");
      out.write("               <h2 style=\"border-radius: 0.5rem;box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%);width:700px;margin-left:350px\">  ORGANIC Healthy Food Grown by Farmers  </h2>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div></a>\r\n");
      out.write("   </section>\r\n");
      out.write("<section id=\"organic1\" style=\"margin-left:280px;\">\r\n");
      out.write(" <a href=\"../firstpage.jsp\"> <h1 style=\"position:absolute;top:1590px;margin-left:440px;color:white;text-align:center;\"><button class=\"main-btn1\" >Visit Organic Farming</button></h1></a>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- section-9 footer-->\r\n");
      out.write("  <footer id=\"footer\" class=\"footer\" style=\"position:absolute;top:1720px;width:100%;\">\r\n");
      out.write("    <div class=\"footer py-5\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("            <a class=\"footer-link\" href=\"#doc\">Documents</a>\r\n");
      out.write("            <a class=\"footer-link\" href=\"#organic\">Organic</a>\r\n");
      out.write("            <a class=\"footer-link\" href=\"#cat\">Categories</a>\r\n");
      out.write("            <a class=\"footer-link\" href=\"#slide\">Services</a>\r\n");
      out.write("            <div class=\"footer-social pt-4 text-center\">\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-pinterest\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("              <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-12\">\r\n");
      out.write("            <div class=\"footer-copy\">\r\n");
      out.write("              <div class=\"copy-right text-center pt-5\">\r\n");
      out.write("                <p class=\"text-light\">Â© 2021. VIP. All rights reserved.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
